// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RainforestApi;

#nullable disable

namespace RainforestApi.Migrations
{
    [DbContext(typeof(RainforestContext))]
    [Migration("20250520030321_AddHashPrice")]
    partial class AddHashPrice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("RainforestApi.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Progress")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuotedAcceptedHashes")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("text");

                    b.Property<string>("StratumUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RainforestApi.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceUSD")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShippingRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("RainforestApi.Models.Order", b =>
                {
                    b.HasOne("RainforestApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("RainforestApi.Models.DatumResponse", "MinerResponse", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("AcceptedDiff")
                                .HasColumnType("INTEGER")
                                .HasAnnotation("Relational:JsonPropertyName", "accepted_diff");

                            b1.Property<int>("AcceptedShares")
                                .HasColumnType("INTEGER")
                                .HasAnnotation("Relational:JsonPropertyName", "accepted_shares");

                            b1.Property<int>("Cid")
                                .HasColumnType("INTEGER")
                                .HasAnnotation("Relational:JsonPropertyName", "cid");

                            b1.Property<int>("Difficulty")
                                .HasColumnType("INTEGER")
                                .HasAnnotation("Relational:JsonPropertyName", "diff");

                            b1.Property<double>("HashrateTerahashesPerSecond")
                                .HasColumnType("REAL")
                                .HasAnnotation("Relational:JsonPropertyName", "hashrate_ths");

                            b1.Property<string>("Host")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasAnnotation("Relational:JsonPropertyName", "host");

                            b1.Property<int>("RejectedDiff")
                                .HasColumnType("INTEGER")
                                .HasAnnotation("Relational:JsonPropertyName", "rejected_diff");

                            b1.Property<int>("RejectedShares")
                                .HasColumnType("INTEGER")
                                .HasAnnotation("Relational:JsonPropertyName", "rejected_shares");

                            b1.Property<double>("SubscribeSecs")
                                .HasColumnType("REAL")
                                .HasAnnotation("Relational:JsonPropertyName", "subscribe_secs");

                            b1.Property<bool>("Subscribed")
                                .HasColumnType("INTEGER")
                                .HasAnnotation("Relational:JsonPropertyName", "subscribed");

                            b1.Property<int>("Thread")
                                .HasColumnType("INTEGER")
                                .HasAnnotation("Relational:JsonPropertyName", "thread");

                            b1.Property<string>("UserAgent")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasAnnotation("Relational:JsonPropertyName", "useragent");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasAnnotation("Relational:JsonPropertyName", "username");

                            b1.HasKey("OrderId");

                            b1.ToTable("DatumResponse", (string)null);

                            b1.WithOwner("Order")
                                .HasForeignKey("OrderId");

                            b1.Navigation("Order");
                        });

                    b.Navigation("MinerResponse");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
