// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RainforestApi;

#nullable disable

namespace RainforestApi.Migrations
{
    [DbContext(typeof(RainforestContext))]
    partial class RainforestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("RainforestApi.Models.DatumResponse", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "username");

                    b.Property<int>("AcceptedDiff")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "accepted_diff");

                    b.Property<int>("AcceptedShares")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "accepted_shares");

                    b.Property<int>("Cid")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "cid");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "diff");

                    b.Property<double>("HashrateTerahashesPerSecond")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "hashrate_ths");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "host");

                    b.Property<int>("RejectedDiff")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "rejected_diff");

                    b.Property<int>("RejectedShares")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "rejected_shares");

                    b.Property<double>("SubscribeSecs")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "subscribe_secs");

                    b.Property<bool>("Subscribed")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "subscribed");

                    b.Property<int>("Thread")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "thread");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "useragent");

                    b.HasKey("Username");

                    b.ToTable("DatumResponse");
                });

            modelBuilder.Entity("RainforestApi.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MinerResponseUsername")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Progress")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuotedAcceptedSharePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("text");

                    b.Property<string>("StratumUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MinerResponseUsername");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RainforestApi.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceInAcceptedShares")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("RainforestApi.Models.Order", b =>
                {
                    b.HasOne("RainforestApi.Models.DatumResponse", "MinerResponse")
                        .WithMany()
                        .HasForeignKey("MinerResponseUsername");

                    b.HasOne("RainforestApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MinerResponse");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
